"""Creando tabla TreatmentData

Revision ID: 8b4bb9c184e5
Revises: 
Create Date: 2023-12-02 02:32:48.590935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4bb9c184e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatmentdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatmentNumber', sa.Integer(), nullable=True),
    sa.Column('playerName', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('miniGameName', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('ObjectCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatmentdata')
    # ### end Alembic commands ###
